### ISSUE TITLE
Handling of non-ASCII commit messages in emails sent

### ISSUE THREAD

**Issue by jsm28** [AdaCore/git-hooks#11]
(This is something I noticed a while back in the use of these hooks by glibc, and experiment confirms it's present for the installation used by GCC.)

Emails sent out for commits by the hooks are marked 'Content-Type: text/plain; charset="us-ascii"'. This applies even if there is non-ASCII content in the email. If the content (including author name, commit message contents and diffs) is not ASCII, but is valid UTF-8, it almost certainly *is* encoded in UTF-8, and the email headers should specify charset="utf-8" accordingly.

**Comment by jwakely** [comment]
For example https://gcc.gnu.org/ml/gcc-cvs/2020-01/msg00782.html is for a commit with UTF-8 in the changelog, but the 2-byte UTF-8 sequence in the Author field is escaped as `&#xC3;&#xA7;` rather than `&#xE7;` (or just being left untouched). The 'raw text' link shows the content-type of the email did say `us-ascii`.

**Comment by brobecke** [comment]
Hello. The following commit should fix this issue:

  | commit ff8859e9ac086ab0c829e1134a08fe377a2a13c9
  | Author: Joel Brobecker <brobecker@adacore.com>
  | Date:   Sun Jul 26 15:16:49 2020 -0700
  | Subject: Incorrect Content-Type charset for emails with non-ascii chars in email body
