### ISSUE TITLE
git hooks encoding issues

### ISSUE THREAD

**Issue by jakubjelinek** [AdaCore/git-hooks#13]
We are experiencing lost emails from gcc commits and today with some logging instrumentation traced it to:
'ascii' codec can't decode byte 0xe2 in position 4882: ordinal not in range(128)                                                                   
Traceback (most recent call last):                                                                                                                 
  File "hooks/post_receive.py", line 87, in post_receive                                                                                           
  File "/sourceware1/projects/src-home/git-hooks/hooks/daemon.py", line 82, in run_in_daemon                                                       
    fun()                                                                                                                                          
  File "/sourceware1/projects/src-home/git-hooks/hooks/updates/emails.py", line 107, in flush                                                      
    email.send()                                                                                                                                   
  File "/sourceware1/projects/src-home/git-hooks/hooks/updates/emails.py", line 233, in send                                                       
    e_msg_body = self.__email_body_with_diff                                                                                                       
  File "/sourceware1/projects/src-home/git-hooks/hooks/updates/emails.py", line 310, in __email_body_with_diff                                     
    email_body += diff                                                                                                                             
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4882: ordinal not in range(128)                                               
(the exact lines might be different from upstream because we've added the logging in there).
The last few missing mails we've checked all had some non-ascii but valid utf-8 characters somewhere in git diff.
E.g.
https://gcc.gnu.org/pipermail/gcc-cvs/2020-August/331064.html
shows that non-ascii utf-8 characters aren't fatal in the commit message and even the subject etc. look properly encoded:
From: =?iso-8859-1?q?Jos=E9_Rui_Faustino_de_Sousa?= <jrfsousa@gcc.gnu.org>
Subject: =?utf-8?q?=5Bgcc_r11-2940=5D_=092020-8-20__Jos=C3=A9_Rui_Faustino_de_Sous?=
 =?utf-8?q?a__=3Cjrfsousa=40gmail=2Ecom=3E?=
X-Git-Author: =?utf-8?q?Jos=C3=A9_Rui_Faustino_de_Sousa?= <jrfsousa@gmail.com>
but
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable
looks wrong when the body contains utf-8 and not just ascii.

Anyway, could the hooks be changed such that it uses charset="utf-8" for the mail bodies (at least if the body is valid utf-8)?
And, could __email_body_with_diff be fixed such that it does the git diff handling as if it was utf-8 and perhaps have some fallback in case either the git diff or the commit message is not valid utf-8, say try iso-8859-15 or similar encoding as fallback?
Better to get a badly encoded mail than no mail at all.  Especially for bugzilla integration not sending a mail means bugs don't get updated with git commit fixes.

**Comment by jakubjelinek** [comment]
email_body = self.email_body
        if self.diff is not None:
            # Append the "Diff:" marker to email_body, followed by
            # the diff. Truncate the patch if necessary.
            diff = self.diff
            max_diff_size = git_config('hooks.max-email-diff-size')
            if len(diff) > max_diff_size:
                diff = diff[:max_diff_size]
                diff += ('[...]\n\n[diff truncated at %d bytes]\n'
                         % max_diff_size)

            email_body += '\nDiff:\n'
            email_body += diff
The traceback is on the last line above.
The last commit with missing emails is
https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=421d0d0f54294a7bf2872b3b2ac521ce0fa9869e
as can be seen in:
https://gcc.gnu.org/pipermail/gcc-cvs/2020-November/date.html :
[gcc r11-4955] libgccjit.h: fix typo in comment   David Malcolm
[gcc r11-4956] jit: fix string escaping   David Malcolm
[gcc(refs/users/wschmidt/heads/builtins4)] rs6000: Revise altivec.h to use rs6000-vecdefines.h   William Schmidt
[gcc r11-4958] libstdc++: Optimise std::future::wait_for and fix futex polling   Jonathan Wakely 
The [gcc r11-4957] ... mail just isn't there.

**Comment by marxin** [comment]
@brobecke

**Comment by marxin** [comment]
One sub-request would be to add a top-level `try-except` block and do a proper logging.

**Comment by brobecke** [comment]
@jakubjelinek , Thanks for the report.

I'm running out of time for this weekend, unfortunately. What I can say is that I haven't been able to reproduce so far.
I think it has something to do with the configuration being used by the GCC repository. After not being able to reproduce
with a small reproducer where the "diff" had non-ascii characters, I tried with the  exact commit highlighted above
(https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=421d0d0f54294a7bf2872b3b2ac521ce0fa9869e), as follow:

(a) create a --bare clone of the gcc repository
(b) in that bare clone, create a refs/meta/config branch, with the following project.config:

```
[hooks]
        from-domain = adacore.com
        mailinglist = brobecker@adacore.com
```
(c) Define the following environment variables:

```
$ export GIT_HOOKS_USER_NAME=brobecke
$ export GIT_HOOKS_USER_FULL_NAME='Joel Brobecker'\n
$ export GIT_HOOKS_TESTSUITE_MODE=true
```

The latter in particular is there to tell the hooks we are in "testing" mode, which makes the email be dumped on stdout rather than being sent.

(d) trigger the `post-receive` hook as follow:

```
$ cd /path/to/bare-repo.git
$ echo "fec573408310139e1ffc42741fbe46b4f2947592 421d0d0f54294a7bf2872b3b2ac521ce0fa9869e refs/heads/master" | ./hooks/post-receive
```

The above is doing reproducing what would happen in terms of email sending, and I got everything as expected. Here is an except for the output I got:

```
$ echo "fec573408310139e1ffc42741fbe46b4f2947592 421d0d0f54294a7bf2872b3b2ac521ce0fa9869e refs/heads/master" | ./hooks/post-receive
DEBUG: MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset="utf-8"
From: Joel Brobecker <brobecke@adacore.com>
To: brobecker@adacore.com
Subject: [bare-gcc-public] jit: add support for inline asm [PR87291]
X-Act-Checkin: bare-gcc-public
X-Git-Author: David Malcolm <dmalcolm@redhat.com>
X-Git-Refname: refs/heads/master
X-Git-Oldrev: fec573408310139e1ffc42741fbe46b4f2947592
X-Git-Newrev: 421d0d0f54294a7bf2872b3b2ac521ce0fa9869e

commit 421d0d0f54294a7bf2872b3b2ac521ce0fa9869e
Author: David Malcolm <dmalcolm@redhat.com>
Date:   Thu Nov 12 17:28:17 2020 -0500

    jit: add support for inline asm [PR87291]
[snip snip snip]
Diff:
---
[snip snip snip]
```

As we can see, no crash. The email's content -type is also correctly set to "utf-8".

The answer to reproducing the problem must be in one of the options and/or scripts that the gcc repository uses. I can see the git-hooks config in GCC's project.config, but I do not have access to the scripts themselves.

Do you think you guys could investigate a bit more using the trick I just showed? Once I understand the problem, it should be pretty quick to fix. If not able to investigate more, one option might be for me to request access to those scripts. Or if that fails, I will see if we can determine the potential source of the problem from code inspection.

**Comment by brobecke** [comment]
A couple of things I forgot mentioning in my previous email:

- I installed the hooks in my local copy of the bare repository!
- I also tried the same command above, but after having unset the `GIT_HOOKS_TESTSUITE_MODE` environment variable. Instead of getting the debug trace, the email got sent to me, and again, everything was as expected.

**Comment by marxin** [comment]
Thank you Joel for the help.

I reproduced your steps and I can't really reproduce that problem locally in a dry mode. To be honest, I've got quite some experience using Python, but Python2 and it's work with unicode and non-unicode strings is all Greek to me.

My recommendation would be to always use `utf8` rather than `ascii` as all ascii chars are valid also for unicode.
So maybe we can change `guess_encoding` to only try `utf8` and `iso-8859-1`.

One unrelated question: are you planning to port the script to Python 3? Or is it too much to port?

**Comment by jakubjelinek** [comment]
As we know what to look at in the problematic commit (just ensure that the git diff contains some non-ascii utf-8), could we (after stage1 is over) try some commits in the gcc-reposurgeon repo and if we can easily reproduce missing mails from that repo, perhaps add some extra logging to debug what is really going on.
Unfortunately, the useless mail archiver we use now doesn't really show mail headers so it is impossible to check if gdb-cvs mails are really utf-8 content encoding, gcc-cvs mails certainly aren't.  But I don't really see Content-Type string anywhere in the git hooks script, so it is unclear what emits that.

**Comment by marxin** [comment]
> As we know what to look at in the problematic commit (just ensure that the git diff contains some non-ascii utf-8), could we (after stage1 is over) try some commits in the gcc-reposurgeon repo and if we can easily reproduce missing mails from that repo, perhaps add some extra logging to debug what is really going on.

Yes, I've just made a couple of commits to the repository and one can easily reproduce that.
So I would add the following debugging patch:

```patch
diff --git a/sourceware/projects/src-home/git-hooks/hooks/updates/emails.py b/sourceware/projects/src-home/git-hooks/hooks/updates/emails.py
index 44d900a..9fa30dc 100644
--- a/sourceware/projects/src-home/git-hooks/hooks/updates/emails.py
+++ b/sourceware/projects/src-home/git-hooks/hooks/updates/emails.py
@@ -307,7 +307,11 @@ class Email(object):
                          % max_diff_size)
 
             email_body += '\nDiff:\n'
+            with open("/tmp/gcc-git-mail.log", "a") as f:
+                f.write(email_body)
+                f.write(diff)
             email_body += diff
+
         return email_body
 
     def __call_filer_cmd(self):
```

**Comment by brobecke** [comment]
> I reproduced your steps and I can't really reproduce that problem locally in a dry mode. To be honest, I've got quite some experience using Python, but Python2 and it's work with unicode and non-unicode strings is all Greek to me.
> 
> My recommendation would be to always use `utf8` rather than `ascii` as all ascii chars are valid also for unicode.
> So maybe we can change `guess_encoding` to only try `utf8` and `iso-8859-1`.

I think the problem is happening because of something elsewhere. For the email body, the `guess_encoding` function is called for the entire email body, including the diff, so after the offending string concatenation.

> One unrelated question: are you planning to port the script to Python 3? Or is it too much to port?

I've been wanting to do that for a year, now, and this unfortunately took a backseat because I worked on all the enhancements for the GCC community ;-) ! It's on my list, but again, it's a weekend project, and I expect it'll take a good few months to complete. The transition itself shouldn't be too bad, but there's the testsuite which I want to transition to pytest.

**Comment by davidmalcolm** [comment]
Python 2 is notoriously fiddly when it comes to encoding.  In particular, **the behavior changes depending on whether stdout is directly connected to a tty**.  The latter affects the `unicode_default_encoding` internal variable (queryable via `sys.getdefaultencoding()`), which affects every PyUnicodeObject in the interpreter.

In Python 3, the default value of unicode_default_encoding is "utf-8", whereas in Python 2 it is "utf-8" if stdout is connected to a tty, but "ascii" otherwise.

```
# Printing non-ASCII unicode to stderr from Python 2 works if connected to a tty:
$ python2 -c "print(u'\u03b1\u03b2\u03b3')"
αβγ

# ...but fails when piping into "cat":
$ python2 -c "print(u'\u03b1\u03b2\u03b3')" | cat
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

This is a big "gotcha" when debugging Python2 scripts, pipelines, daemons and cronjobs etc.

You can set `PYTHONIOENCODING=utf-8` in the environment to set the default for python 2 to UTF-8 (regardless of tty):

```
$ PYTHONIOENCODING=utf-8 python2 -c "print(u'\u03b1\u03b2\u03b3')" | cat
αβγ
```
This makes Python 2 behave much more like Python 3 in this respect.

Perhaps this might help fix the issues?

**Comment by marxin** [comment]
All right, thanks to @jakubjelinek we have a reproducer:

```
$ cat project.config 
[hooks]
        from-domain = adacore.com
        mailinglist = brobecker@adacore.com
	commit-email-formatter = /tmp/gcc/copy.py
```

```
$ cat /tmp/gcc/copy.py 
#!/usr/bin/env python3

import sys
import json

json.dump({'email_body': 'body', 'email_subject': 'subject'}, sys.stdout)
```

```
$ echo "fec573408310139e1ffc42741fbe46b4f2947592 421d0d0f54294a7bf2872b3b2ac521ce0fa9869e refs/heads/master" | /tmp/git-hooks/hooks/post-receive
Traceback (most recent call last):
  File "/tmp/git-hooks/hooks/post_receive.py", line 118, in <module>
    post_receive(refs_data, args.submitter_email)
  File "/tmp/git-hooks/hooks/post_receive.py", line 71, in post_receive
    run_in_daemon(email_queue.flush)
  File "/tmp/git-hooks/hooks/daemon.py", line 82, in run_in_daemon
    fun()
  File "/tmp/git-hooks/hooks/updates/emails.py", line 103, in flush
    email.send()
  File "/tmp/git-hooks/hooks/updates/emails.py", line 229, in send
    e_msg_body = self.__email_body_with_diff
  File "/tmp/git-hooks/hooks/updates/emails.py", line 303, in __email_body_with_diff
    email_body += diff
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4882: ordinal not in range(128)
```

So problem is that `json.loads` returns unicode strings:

```python2
>>> import json
>>> json.loads('["foo", {"bar":["baz", null, 1.0, 2]}]')
[u'foo', {u'bar': [u'baz', None, 1.0, 2]}]
```

**Comment by davidmalcolm** [comment]
Note to self: I wrote up some notes on Python 2 unicode encoding issues here: https://fedoraproject.org/wiki/Features/PythonEncodingUsesSystemLocale (a rejected Fedora change)

**Comment by brobecke** [comment]
> All right, thanks to @jakubjelinek we have a reproducer:

Thanks very much for the reproducer. That's really taking me by surprise! I will take a look and make it a priority for this weekend.

**Comment by brobecke** [comment]
Small update: This issue certainly forced me to investigate a lot of different questions! Those questions revolved around unicode strings, email contents encoding as well as Content-Transfer-Encoding, the various classes available for sending email, all this multiplied by the differences between the Python 2.7 implementation the Python 3.x implementation (with 3.x >= 3.8 for me).

I really wanted to address this issue in a way that would work for both Python 2.x and Python 3.x, but everything indicates that this is going to require  a few small design changes. Given the time that I have, and the relatively pressing need to avoid those missing emails, a localized patch is in the works. I Hope to have it pushed early next week. The rest will be take care of later.

**Comment by brobecke** [comment]
For the record, I am planning on installing this change at AdaCore tomorrow morning, and then on sourceware.org the next day.

**Comment by marxin** [comment]
Thank you for the fix.

**Comment by brobecke** [comment]
You are very welcome. I confirm I installed the fix on sourceware this morning (I believe GCC uses the same install as GDB's right?).

**Comment by marxin** [comment]
Thanks!
I can confirm it works, I've just tested that:
https://gcc.gnu.org/pipermail/gcc-cvs/2020-November/337810.html

**Comment by brobecke** [comment]
> Thanks!
> I can confirm it works, I've just tested that:
> https://gcc.gnu.org/pipermail/gcc-cvs/2020-November/337810.html

Neat :smiley:. Thanks for confirming!
