### ISSUE TITLE
Accept commit messages in UTF-8 rather than ISO-8859-15

### ISSUE THREAD

**Issue by simark** [AdaCore/git-hooks#14]
It is quite common to copy-paste compiler error messages in commit messages when fixing build issues.  gcc error messages contain UTF-8 quotation marks, which leads to:

```
remote: *** Invalid revision history for commit 4cd78db33cc34a33060faaf9d97adef0fc60a0ac:
remote: *** It contains characters not in the ISO-8859-15 charset.
remote: ***                    
remote: *** Below is the first line where this was detected (line 6):
remote: *** |     /home/simark/src/binutils-gdb/gdb/f-lang.c: In function 'value* fortran_value_subarray(value*, expression*, int*, int, noside)’:
remote: ***                                                                                                                                     ^
remote: ***                                                                                                                                     |
remote: ***                                                                                      
remote: *** Please amend the commit's revision history to remove it
remote: *** and try again.                                                                       
remote: error: hook declined to update refs/heads/master
```

In this day and age, I think it would make sense to accept UTF-8 messages.

**Comment by brobecke** [comment]
This check was introduced because we found that people accidentally copy/pasted non-printable characters without realizing it, and that sometimes those non-printable characters were affecting the behavior of some tools that parse those commit messages. Projects can, however, turn this check of using the option `hooks.no-rh-character-range-check`. I can make the change for the GDB project.

**Comment by simark** [comment]
Well, I think it's a good idea to check that commit messages contain only valid text (including for GDB), just that it would make sense to use UTF-8, since everything is UTF-8 nowadays.

**Comment by brobecke** [comment]
> Well, I think it's a good idea to check that commit messages contain only valid text (including for GDB), just that it would make sense to use UTF-8, since everything is UTF-8 nowadays.

Sure. 

With the current version of the hooks, which are Python2-only, I'm not entirely sure about the level of encoding verification.

When the hooks are converted to Python3 (a weekend project I am hoping to start early 2021 and finish a few months later), I think we'll have that check done implicitly, since strings need to have an encoding.

**Comment by simark** [comment]
If you think this is a good idea to implement, I can start looking into it myself (I just wanted to make sure it would be useful before I started looking into it).

Transitioning to Python 3 is also something I'm interested in helping with :)

**Comment by brobecke** [comment]
> Transitioning to Python 3 is also something I'm interested in helping with :)

That's awesome team attitude.

The plan for me to transition this project to Python 3 starts with first transitioning the testsuite to pytest, because the testsuite framework I'm using is not common and won't be transitioned to Python 3 either. Once the transition to pytest is done, the hope is that we'll be able to run the testsuite with python Python 2 and Python 3, as which point we just run focus on the errors returned when using Python 3.

Meanwhile, if you'd like to help with that transition, one part that I haven't really looked at yet is all the obvious violations of Python3 (e.g. did I use print statements instead of calling the function, etc). This can be done in parallel to the testsuite transition. I'm not it'll be easy for you to run the testsuite, so you might not be able to test your changes, but I can do that if needed.

> If you think this is a good idea to implement, I can start looking into it myself (I just wanted to make sure it would be useful before I started looking into it).

For that part, I would personally wait for the transition to Python 3 first. String handling is really very different, and although it's a constant pain in the neck that Python3 forces developers to think about these problems right from the get go, it does introduce the nice property that we get exceptions as soon as it finds invalid code points.

**Comment by simark** [comment]
Can we re-open (and reconsider) this now that the transition to Python 3 is complete?

**Comment by brobecke** [comment]
> Can we re-open (and reconsider) this now that the transition to Python 3 is complete?

Sure. I would like to understand a bit more clearly what it is that you'd like us to do.

I think the main issue you have is that iso-8859-15 (latin-15) is overly restrictive for commit messages, and you'd like to expand that to all of UTF-8. We can start by turning the range check completely, which will have the effect of allowing UTF-8.

Theoretically, the git-hooks could support/allow code-points not defined in UTF-8, but in practice, if a commit message or diff has code-points outside of the (ascii, iso-8859-15, or UTF-8) charsets, we'll get an error trying to decode the commit message or diff, and so it'll get rejected. Not sure how cleanly (meaning, we might get a Python exception), but it'll get rejected.

So I guess the question becomes whether the issue is likely enough for us to want to do something about it?

**Comment by simark** [comment]
> Sure. I would like to understand a bit more clearly what it is that you'd like us to do.
>
> I think the main issue you have is that iso-8859-15 (latin-15) is overly restrictive for commit messages, and you'd like to expand that to all of UTF-8. We can start by turning the range check completely, which will have the effect of allowing UTF-8.

Indeed, looking at the ensure_iso_8859_15_only check, it would probably mean just disabling it. I suppose the lines at this point are Python `str` object, so already a sequence of unicode code points (which was likely decode from an UTF-8 source).  The use case shown above (copy pasting gcc error messages) is one example, but also if somebody would like to put 🚀 in their commit message, who are we to stop them ? :)

> Theoretically, the git-hooks could support/allow code-points not defined in UTF-8, but in practice, if a commit message or diff has code-points outside of the (ascii, iso-8859-15, or UTF-8) charsets, we'll get an error trying to decode the commit message or diff, and so it'll get rejected. Not sure how cleanly (meaning, we might get a Python exception), but it'll get rejected.

I think it's reasonable to limit commit messages to UTF-8, and not allow any byte sequences.

> So I guess the question becomes whether the issue is likely enough for us to want to do something about it?

Which issue are you talking about?  The issue of having things representable in UTF-8 but not ISO-8859-15 is real. The issue of wanting to put abritrary bytes in a commit message, not so much.

**Comment by brobecke** [comment]
> > So I guess the question becomes whether the issue is likely enough for us to want to do something about it?
> 
> Which issue are you talking about? The issue of having things representable in UTF-8 but not ISO-8859-15 is real. The issue of wanting to put abritrary bytes in a commit message, not so much.

I meant: Do we want to investigate how the git-hooks behave if someone uses a charset that's not one of the 3 that we currently support, and make sure we generate an understandable message if we detect it. For me I think it's unlikely to be an issue in practice. When I search around for various studies about UTF-8's usage, it seems like it has very nearly taken over.

For the GDB repository, I think we'll be good to go by just disabling the iso-8859-15 range-check if we haven't done so already.

**Comment by simark** [comment]
> I meant: Do we want to investigate how the git-hooks behave if someone uses a charset that's not one of the 3 that we currently support, and make sure we generate an understandable message if we detect it. For me I think it's unlikely to be an issue in practice. When I search around for various studies about UTF-8's usage, it seems like it has very nearly taken over.

I'd be curious to see (although I do not care much in the end).  If someone sent a commit message encoded as ISO-8859-15, let's say with an Å (encoded as 0xC3), would it even work?  I suppose the git Python module would try to decode the commit as UTF-8, and that would probably fail.

> For the GDB repository, I think we'll be good to go by just disabling the iso-8859-15 range-check if we haven't done so already.

That would be fine with me :).

**Comment by brobecke** [comment]
> > I meant: Do we want to investigate how the git-hooks behave if someone uses a charset that's not one of the 3 that we currently support, and make sure we generate an understandable message if we detect it. For me I think it's unlikely to be an issue in practice. When I search around for various studies about UTF-8's usage, it seems like it has very nearly taken over.
> 
> I'd be curious to see (although I do not care much in the end). If someone sent a commit message encoded as ISO-8859-15, let's say with an Å (encoded as 0xC3), would it even work? I suppose the git Python module would try to decode the commit as UTF-8, and that would probably fail.

Not quite: The git-hooks tries to decode each line first using UTF-8, and if that fails, then tries iso-8859-15. So if the commit message uses a character with an accent using the ISO-8859-15 encoding, it'll still work. What will happen is that we'll process the commit message, converting it to unicode internally. After that, I can't remember for sure what encoding is used to send the email, but I think it's UTF-8. Either way, the encoding and the message body match, so there shouldn't be any discrepancies causing incorrect displays in mailers.

**Comment by brobecke** [comment]
Hi @simark,

> > For the GDB repository, I think we'll be good to go by just disabling the iso-8859-15 range-check if we haven't done so already.
> 
> That would be fine with me :).

Just a quick note to confirm I've just pushed a change to the gdb repository's configuration:

+        # We allow characters outside the ISO-8859-15 charset.
+        no-rh-character-range-check = true
