### ISSUE TITLE
Custom branch and tag naming conventions

### ISSUE THREAD

**Issue by jsm28** [AdaCore/git-hooks#4]
Filing feature requests for GCC use of these hooks as issues here, as requested by Joel.

For use of these hooks in the GCC repository, we found we needed to make changes to support custom branch and tag naming conventions, and it would be good if that could be configured without needing local changes to the hooks. There are I think three closely related pieces here:

* Additional patterns for branch and tag names (GCC uses names under refs/users/ and refs/vendors/).
* Restrictions on valid patterns for branch and tag names within those allowed by default (GCC restricts the form of valid branch names under refs/heads/, so preventing various accidental pushes that would create a badly named branch).
* The configuration of which branches allow non-fast-forward pushes needs to work with such custom names rather than only allowing configuring names under refs/heads/.

https://gcc.gnu.org/ml/gcc/2020-01/msg00143.html suggests combining the first two into one configuration setting for branch patterns and one for tag patterns, hence filing them in the same issue.

**Comment by brobecke** [comment]
This was implemented by the commit highlighted below (and a few preparatory patches before it)

For GCC, the configuration should look like the following:

# Only master and release branches are allowed in the standard namespace for branches.
use-standard-branch-ref-namespace = false
branch-ref-namespace = refs/heads/master
branch-ref-namespace = refs/heads/releases/gcc-.*
# Vendor and users branches have a dedicated reference namespace because [xxx].
branch-ref-namespace = refs/users/.*
branch-ref-namespace = refs/vendors/.*

Similar support was added for tags (see README.md for more info, the name of the options being the same where s/branch/tag/).

Also, the hooks.non-fast-forward-config option was modified to match the entire reference name,
allowing support for these custom reference namespaces.

| commit d1a76a87a868351c47698342bacb6d978d61cd4a
| Author: Joel Brobecker <brobecker@adacore.com>
| Date:   Mon Feb 17 08:34:26 2020 +0400
| Subject: Change the hooks.non-fast-forward config to match the entire ref name
| 
| This lifts a limitation where non-fast-forward updates could only be
| allowed for references whose name start with 'refs/heads/' (the
| standard namespace for branches). As it happens, GCC is using branch
| names in a different namespace. So this commit changes this config
| option to match the entire reference name, rather than just the branch
| name. There is a break in compatibility for the repositories already
| using this configuration, but this change takes care of detecting
| this situation and provide an informative message explaining the likely
| situation.


| commit febc78150e555de616cc001e30b6546e5ec695a3
| Author: Joel Brobecker <brobecker@adacore.com>
| Date:   Tue Apr 28 14:30:05 2020 -0700
| Subject: Add support for branch and tag custom namespaces
|
| The idea is to introduce a new set of configuration options allowing
| repositories to set alternate naming up for branches and tags.
| And, in order to have the default to recognize all standard names
| while at the same time give users an option to restrict the name
| of the branches/tags that one can have in the standard naming,
| we are introducing another option called...
|
|     use-standard-{branch,tag}-ref-namespace
|
| ... whose default is True.
|
| For repositories that want to add alternate naming schemes without
| restrictions in the standard branch/tag namespaces, they just add
| the alternate branch/tags names via (with "xxx" being a regular
| expression):
|
|     {branch,tag}-ref-namespace = xxx
|
| For repositories that want to restrict the branch/tag naming within
| the standard namespaces, they start by dropping the standard
| ref naming, and then add the ref-naming that they want to allow:
|
|     use-standard-{branch,tag}-ref-namespace = false
|     {branch,tag}-ref-namespace = xxx
|     {branch,tag}-ref-namespace = yyy
|
| To support this feature, the engine for determining the type of
| update we are facing has been made more dynamic. Because things
| are more flexible, it can be harder to understand what is happening
| when users are faced with an error. In that context, a reasonable
| amount of effort is spent trying to provide helpful error messages
| for the more common error cases. More far-fetched scenarios are
| covered by testing, but no effort is made to provide detailed
| diagnostic (at least not yet).
