### ISSUE TITLE
Custom checks on commit messages

### ISSUE THREAD

**Issue by jsm28** [AdaCore/git-hooks#7]
Filing feature requests for GCC use of these hooks as issues here, as requested by Joel.

It would be useful to have somewhere to hook in custom checks on commit messages without needing to patch the scripts, possibly config options specifying regular expressions not permitted to match the first line, or any line, of the commit message.

We have at least three uses for such a check in GCC:

* We reject a first line of a commit message that looks like a GNU ChangeLog header (matches `[0-9]{4}-[0-9]{2}-[0-9]{2} .*<.*@.*>`).
* We'd like to reject a first line of a commit message that starts with whitespace, but that's hard in the present framework because leading whitespace from the output of any git command gets stripped early.
* We reject a commit message if any line starts 'From-SVN: ', to avoid confusion of cherry-picks (of commits that were converted from SVN) with commits originally converted from SVN.

The third of these is clearly GCC-specific so needs a suitable configuration hook. The first two seem rather more generic but could also be implemented through such a hook if it's matched against the message without any leading whitespace on the first line being removed.

**Comment by jsm28** [comment]
Another example of a use for this is rejecting single-word summaries such as "gcc/ChangeLog:", which is another kind of mistake people coming from SVN are liable to make.

**Comment by brobecke** [comment]
Hi Joseph, I'm still working on this feature, but I wanted to let you know that I made the following change...

| commit af06d5ea5479dc67bab342b69a4431865f29e4af (HEAD -> master, origin/master)
| Author: Joel Brobecker <brobecker@adacore.com>
| Date:   Sun Jul 5 09:41:47 2020 -0700
| Subject: git_run: stop strip-ing the start of the command's output

... which at least takes care of point #2 that you were mentioning in your opening message.

Tailing whitespaces are still stripped, because not doing so means that I would have to audit all the places that depend on that behavior. So I left that for later, hoping that we never need it.

I'll work on the hook itself next.

**Comment by brobecke** [comment]
This is now implemented, thanks to the following commit:

| commit 1de3eb14c73289c79d169fe23fc94fe786feb2a9
| Author: Joel Brobecker <brobecker@adacore.com>
| Date:   Sun Jul 19 19:22:29 2020 -0700
| Subject: Add support for new config option hooks.commit-extra-check

I am realizing that there is an unfortunate thinko in the name of the option, and in the doc too. The correct name of the option is `hooks.commit-extra-checker`. I will fix the doc before I close this issue.

**Comment by brobecke** [comment]
Documentation fixed (commit 1109d5c75e88fed80776f6b4c8649bfa597c231c). Closing :-).

**Comment by brobecke** [comment]
Something worth mentioning here for those using sourceware.org's mailing-list. We've been using "git am" to create commits that one-time contributors have sent us, and often the mailing-list would change the author's email to use the mailing-list address instead with "XXX via mailinglist@xxx", which causes the commit's author to be the mailing-list instead of the author's name and email. The GDB/binutils project used this checker to reject such commits.

https://sourceware.org/pipermail/gdb-patches/2020-August/171170.html
